Tensor operators
JetBrains-Research/kinference-compiler pull request #12
Opened 2021-08-16 13:11 UTC by isomethane

2021-08-16 15:23 UTC, nbirillo requested changes

2021-08-16 15:23 UTC, nbirillo commented on core/src/jvmMain/kotlin/io/kinference/compiler/generation/operators/tensor/ConcatGenerator.kt
> +                TODO()
Please, add a message

2021-08-17 15:37 UTC, isomethane commented on core/src/jvmMain/kotlin/io/kinference/compiler/generation/operators/tensor/ConcatGenerator.kt
> +                TODO()
I implemented this case

2021-08-19 11:40 UTC, nbirillo approved these changes
Great!

2021-08-19 11:40 UTC, merged