Simple model code generation
JetBrains-Research/kinference-compiler pull request #7
Opened 2021-07-21 08:12 UTC by isomethane

2021-07-21 09:26 UTC, nbirillo requested changes
Great! But also fix please comments that were discussed in Slack. Also, please, add Github Actions and base architecture for the testing of generation

2021-07-21 09:26 UTC, nbirillo commented on gradle-plugin/src/jvmMain/kotlin/io/kinference/compiler/gradle/GenerateModelSourceTask.kt
> +open class GenerateModelSourceTask : DefaultTask() {
Please, add some description since it is a very important input point

2021-07-21 09:26 UTC, nbirillo commented on gradle-plugin/src/jvmMain/kotlin/io/kinference/compiler/gradle/KInferenceCompilerGradlePlugin.kt
> +        target.task(mapOf("type" to GenerateModelSourceTask::class.java), "generateModelSource")
Can we use a const for generateModelSource?

2021-07-21 09:26 UTC, nbirillo commented on core/src/jvmMain/kotlin/io/kinference/compiler/generation/operators/SimpleOperatorGenerator.kt
> +abstract class SimpleOperatorGenerator(
Please, add a description for this base class

2021-07-21 09:26 UTC, nbirillo commented on core/src/jvmMain/kotlin/io/kinference/compiler/generation/operators/BaseOperatorGenerator.kt
> +abstract class BaseOperatorGenerator(protected val nameMapping: (String) -> String) : CodeBlockGenerator()
Please, add a description for this base class

2021-07-21 09:26 UTC, nbirillo commented on core/src/jvmMain/kotlin/io/kinference/compiler/generation/operators/math/MulGenerator.kt
> +class MulGenerator(
You have almost the same classes for + and *. Probably - and / will be almost the same. Can you reuse the common part of the code? For example by using a new abstract class for base math operators?

2021-07-21 09:26 UTC, nbirillo commented on core/src/jvmMain/kotlin/io/kinference/compiler/generation/operators/OperatorGenerator.kt
> +class OperatorGenerator(
Should we add some comment somewhere that we should add a new operator into this generator? Maybe to the base class

2021-07-21 09:26 UTC, nbirillo commented on core/src/jvmMain/kotlin/io/kinference/compiler/generation/operators/DefaultOperatorGenerator.kt
> +class DefaultOperatorGenerator(
Please, add base description to understand situations when we should use this operator instead someone else

2021-07-21 09:26 UTC, nbirillo commented on core/src/jvmMain/kotlin/io/kinference/compiler/generation/models/Generator.kt
> +abstract class Generator<T> {
Please, add description for this base class

2021-07-21 09:26 UTC, nbirillo commented on core/src/jvmMain/kotlin/io/kinference/compiler/generation/initializers/InitializerGenerator.kt
> +class InitializerGenerator(
Please, add a description

2021-07-21 09:26 UTC, nbirillo commented on core/src/jvmMain/kotlin/io/kinference/compiler/generation/ModelSourceGenerator.kt
> +                .indent("    ")
Probably you can add a constant with indent

2021-07-21 09:26 UTC, nbirillo commented on api/src/jvmMain/kotlin/io/kinference/compiler/serialization/JvmArraySerialization.kt
> +actual fun Array<ShortArray>.toByteArray(): ByteArray {
These functions look very similar. Can we reuse one common function or something like this?

2021-07-21 09:26 UTC, nbirillo commented on api/src/jvmMain/kotlin/io/kinference/compiler/serialization/JvmArraySerialization.kt
> +actual fun ByteArray.toShortTiledArray(blockSize: Int, blocksNum: Int): Array<ShortArray> {
These functions look very similar. Can we reuse one common function or something like this?

2021-07-21 09:26 UTC, nbirillo commented on core/src/jvmMain/kotlin/io/kinference/compiler/generation/ModelClassGenerator.kt
> +class ModelClassGenerator(
Please, add a comment

2021-07-21 09:26 UTC, nbirillo commented on core/src/jvmMain/kotlin/io/kinference/compiler/generation/ModelClassGenerator.kt
> +            add(")\n")
I am not sure but should we use System.getProperty("line.separator")?

2021-08-16 09:06 UTC, cupertank commented on core/src/jvmMain/kotlin/io/kinference/compiler/generation/ModelSourceGenerator.kt
> +        var indent = "    "
const val лучше 😎

2021-08-16 09:07 UTC, cupertank commented on core/src/jvmMain/kotlin/io/kinference/compiler/generation/info/TensorInfo.kt
> +    operator fun component3(): Tensor? = tensor
Лучше сделать TensorInfo дата классом и эти функции будут автоматически генериться

2021-08-17 14:03 UTC, closed without merging